---

# This role installs RKE2 on control plane
# nodes and on worker nodes that are
# RHEL/CentOS based.

# Checks if Red Hat system
- name: REQUIRES YUM based system
  meta: stop_play
  when: ansible_os_family != 'RedHat'

# Setup Yum repos
- include: yum.yml
  become: yes

# Setup...
- import_tasks: config.yml

# Firewalld | disable
- name: FIREWALLD | disable
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: no

# CIS mode
- import_tasks: cis-profile.yml
  when: rke2_cis_mode

- import_tasks: rke2-master.yml